-- 018_tareas.sql -- flujo configurable y trabajo diario. id_objeto/id_media no llevan FK deliberadamente.
CREATE TABLE IF NOT EXISTS tareas_flujos (id_flujo UUID PRIMARY KEY DEFAULT gen_random_uuid(), clave TEXT NOT NULL UNIQUE, nombre TEXT NOT NULL, descripcion TEXT, activo BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tareas_estados (id_estado UUID PRIMARY KEY DEFAULT gen_random_uuid(), id_flujo UUID NOT NULL REFERENCES tareas_flujos(id_flujo) ON DELETE CASCADE, clave TEXT NOT NULL, nombre TEXT NOT NULL, categoria TEXT NOT NULL CHECK (categoria IN ('por_hacer','en_progreso','hecho')), color TEXT, orden INTEGER NOT NULL DEFAULT 0, es_inicial BOOLEAN NOT NULL DEFAULT FALSE, UNIQUE(id_flujo, clave));
CREATE UNIQUE INDEX IF NOT EXISTS uq_tareas_estado_inicial ON tareas_estados(id_flujo) WHERE es_inicial;
CREATE TABLE IF NOT EXISTS tareas_transiciones (id_transicion UUID PRIMARY KEY DEFAULT gen_random_uuid(), id_flujo UUID NOT NULL REFERENCES tareas_flujos(id_flujo) ON DELETE CASCADE, id_estado_origen UUID REFERENCES tareas_estados(id_estado) ON DELETE CASCADE, id_estado_destino UUID NOT NULL REFERENCES tareas_estados(id_estado) ON DELETE CASCADE, clave TEXT NOT NULL, nombre TEXT NOT NULL, orden INTEGER NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(id_flujo, clave));
CREATE TABLE IF NOT EXISTS tareas_reglas_transicion (id_regla UUID PRIMARY KEY DEFAULT gen_random_uuid(), id_transicion UUID NOT NULL REFERENCES tareas_transiciones(id_transicion) ON DELETE CASCADE, fase TEXT NOT NULL CHECK (fase IN ('condicion','validador','post_funcion')), tipo TEXT NOT NULL, configuracion JSONB NOT NULL DEFAULT '{}'::jsonb, mensaje_error TEXT, orden INTEGER NOT NULL DEFAULT 0, activo BOOLEAN NOT NULL DEFAULT TRUE);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tareas_regla_transicion ON tareas_reglas_transicion(id_transicion, fase, tipo, orden);

CREATE TABLE IF NOT EXISTS tareas_espacios (id_espacio UUID PRIMARY KEY DEFAULT gen_random_uuid(), clave TEXT NOT NULL UNIQUE, nombre TEXT NOT NULL, descripcion TEXT, id_flujo UUID REFERENCES tareas_flujos(id_flujo) ON DELETE SET NULL, id_lider UUID REFERENCES usuarios_laboratorio(id_usuario) ON DELETE SET NULL, activo BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tareas (id_tarea UUID PRIMARY KEY DEFAULT gen_random_uuid(), id_espacio UUID NOT NULL REFERENCES tareas_espacios(id_espacio) ON DELETE CASCADE, clave TEXT NOT NULL UNIQUE, titulo TEXT NOT NULL, descripcion TEXT, tipo TEXT NOT NULL DEFAULT 'tarea', prioridad TEXT NOT NULL DEFAULT 'media' CHECK (prioridad IN ('baja','media','alta','critica')), id_estado UUID NOT NULL REFERENCES tareas_estados(id_estado), id_asignado UUID REFERENCES usuarios_laboratorio(id_usuario) ON DELETE SET NULL, id_reportador UUID REFERENCES usuarios_laboratorio(id_usuario) ON DELETE SET NULL, id_padre UUID REFERENCES tareas(id_tarea) ON DELETE SET NULL, fecha_inicio DATE, fecha_limite DATE, completada_at TIMESTAMPTZ, etiquetas TEXT[] NOT NULL DEFAULT '{}', orden_tablero NUMERIC NOT NULL DEFAULT 0, id_objeto UUID, codigo_objeto TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_tareas_espacio_estado ON tareas(id_espacio,id_estado,orden_tablero); CREATE INDEX IF NOT EXISTS idx_tareas_asignado ON tareas(id_asignado) WHERE completada_at IS NULL;
CREATE TABLE IF NOT EXISTS tareas_observadores (id_tarea UUID NOT NULL REFERENCES tareas(id_tarea) ON DELETE CASCADE,id_usuario UUID NOT NULL REFERENCES usuarios_laboratorio(id_usuario) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(id_tarea,id_usuario));
CREATE TABLE IF NOT EXISTS tareas_comentarios (id_comentario UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_tarea UUID NOT NULL REFERENCES tareas(id_tarea) ON DELETE CASCADE,id_autor UUID REFERENCES usuarios_laboratorio(id_usuario) ON DELETE SET NULL,cuerpo TEXT NOT NULL,editado_at TIMESTAMPTZ,eliminado_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tareas_adjuntos (id_adjunto UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_tarea UUID NOT NULL REFERENCES tareas(id_tarea) ON DELETE CASCADE,id_media UUID NOT NULL,nombre TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,subido_por UUID REFERENCES usuarios_laboratorio(id_usuario) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tareas_actividad (id_actividad UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_tarea UUID NOT NULL REFERENCES tareas(id_tarea) ON DELETE CASCADE,id_actor UUID REFERENCES usuarios_laboratorio(id_usuario) ON DELETE SET NULL,tipo TEXT NOT NULL,campo TEXT,antes JSONB,despues JSONB,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_tareas_actividad_tarea ON tareas_actividad(id_tarea,created_at DESC);
CREATE TABLE IF NOT EXISTS tareas_campos (id_campo UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_espacio UUID NOT NULL REFERENCES tareas_espacios(id_espacio) ON DELETE CASCADE,clave TEXT NOT NULL,nombre TEXT NOT NULL,tipo TEXT NOT NULL,configuracion JSONB NOT NULL DEFAULT '{}'::jsonb,requerido BOOLEAN NOT NULL DEFAULT FALSE,orden INTEGER NOT NULL DEFAULT 0,activo BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE(id_espacio,clave));
CREATE TABLE IF NOT EXISTS tareas_valores_campo (id_tarea UUID NOT NULL REFERENCES tareas(id_tarea) ON DELETE CASCADE,id_campo UUID NOT NULL REFERENCES tareas_campos(id_campo) ON DELETE CASCADE,valor JSONB,updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(id_tarea,id_campo));
CREATE TABLE IF NOT EXISTS tareas_esquemas_permisos (id_esquema UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_espacio UUID NOT NULL UNIQUE REFERENCES tareas_espacios(id_espacio) ON DELETE CASCADE,nombre TEXT NOT NULL,activo BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tareas_esquema_reglas (id_regla UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_esquema UUID NOT NULL REFERENCES tareas_esquemas_permisos(id_esquema) ON DELETE CASCADE,accion TEXT NOT NULL CHECK (accion IN ('ver','crear','editar','transicionar','asignar','comentar','adjuntar','eliminar','gestionar')),tipo_sujeto TEXT NOT NULL CHECK (tipo_sujeto IN ('todos','rol','grupo','usuario','asignado','reportador','observador','lider_espacio')),id_sujeto UUID,permitir BOOLEAN NOT NULL DEFAULT TRUE,orden INTEGER NOT NULL DEFAULT 0);

INSERT INTO tareas_flujos(clave,nombre,descripcion) VALUES('basico','Flujo básico','Pendiente → En progreso → En revisión → Hecho') ON CONFLICT(clave) DO UPDATE SET nombre=EXCLUDED.nombre,descripcion=EXCLUDED.descripcion;
WITH f AS (SELECT id_flujo FROM tareas_flujos WHERE clave='basico') INSERT INTO tareas_estados(id_flujo,clave,nombre,categoria,orden,es_inicial) SELECT id_flujo,v.clave,v.nombre,v.categoria,v.orden,v.inicial FROM f CROSS JOIN (VALUES ('pendiente','Pendiente','por_hacer',0,TRUE),('en_progreso','En progreso','en_progreso',1,FALSE),('en_revision','En revisión','en_progreso',2,FALSE),('hecho','Hecho','hecho',3,FALSE)) AS v(clave,nombre,categoria,orden,inicial) ON CONFLICT(id_flujo,clave) DO UPDATE SET nombre=EXCLUDED.nombre,categoria=EXCLUDED.categoria,orden=EXCLUDED.orden,es_inicial=EXCLUDED.es_inicial;
WITH f AS (SELECT id_flujo FROM tareas_flujos WHERE clave='basico'), s AS (SELECT id_estado,clave FROM tareas_estados WHERE id_flujo=(SELECT id_flujo FROM f)) INSERT INTO tareas_transiciones(id_flujo,id_estado_origen,id_estado_destino,clave,nombre) SELECT f.id_flujo,o.id_estado,d.id_estado,v.clave,v.nombre FROM f CROSS JOIN (VALUES ('pendiente','en_progreso','iniciar','Iniciar'),('en_progreso','en_revision','enviar_revision','Enviar a revisión'),('en_revision','hecho','aprobar','Aprobar'),('en_revision','en_progreso','devolver','Devolver'),('hecho','pendiente','reabrir','Reabrir')) v(origen,destino,clave,nombre) JOIN s o ON o.clave=v.origen JOIN s d ON d.clave=v.destino ON CONFLICT(id_flujo,clave) DO UPDATE SET id_estado_origen=EXCLUDED.id_estado_origen,id_estado_destino=EXCLUDED.id_estado_destino,nombre=EXCLUDED.nombre;
WITH t AS (SELECT id_transicion,clave FROM tareas_transiciones WHERE id_flujo=(SELECT id_flujo FROM tareas_flujos WHERE clave='basico')) INSERT INTO tareas_reglas_transicion(id_transicion,fase,tipo,configuracion,mensaje_error,orden) SELECT id_transicion,'condicion','solo_asignado','{}'::jsonb,'Solo la persona asignada puede enviar a revisión.',0 FROM t WHERE clave='enviar_revision' UNION ALL SELECT id_transicion,'validador','campo_requerido','{"campo":"descripcion"}'::jsonb,'Se requiere una descripción antes de aprobar.',0 FROM t WHERE clave='aprobar' UNION ALL SELECT id_transicion,'post_funcion','registrar_actividad','{}'::jsonb,NULL,1 FROM t UNION ALL SELECT id_transicion,'post_funcion','notificar_observadores','{}'::jsonb,NULL,2 FROM t WHERE clave='aprobar' ON CONFLICT (id_transicion,fase,tipo,orden) DO UPDATE SET configuracion=EXCLUDED.configuracion,mensaje_error=EXCLUDED.mensaje_error;
INSERT INTO tareas_espacios(clave,nombre,descripcion,id_flujo) VALUES('TAR','Laboratorio','Trabajo colaborativo del laboratorio',(SELECT id_flujo FROM tareas_flujos WHERE clave='basico')) ON CONFLICT(clave) DO UPDATE SET nombre=EXCLUDED.nombre,descripcion=EXCLUDED.descripcion,id_flujo=EXCLUDED.id_flujo;
INSERT INTO tareas_esquemas_permisos(id_espacio,nombre) VALUES((SELECT id_espacio FROM tareas_espacios WHERE clave='TAR'),'Estándar') ON CONFLICT(id_espacio) DO UPDATE SET nombre=EXCLUDED.nombre;
INSERT INTO contadores(entidad,valor) VALUES('tarea:TAR',0) ON CONFLICT(entidad) DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_tareas_flujos_updated_at') THEN CREATE TRIGGER trg_tareas_flujos_updated_at BEFORE UPDATE ON tareas_flujos FOR EACH ROW EXECUTE FUNCTION set_updated_at(); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_tareas_updated_at') THEN CREATE TRIGGER trg_tareas_updated_at BEFORE UPDATE ON tareas FOR EACH ROW EXECUTE FUNCTION set_updated_at(); END IF;
END $$;
