-- 019_ia_agente.sql -- configuración cifrada, conversaciones y auditoría del agente.
CREATE TABLE IF NOT EXISTS ia_configuracion (id_configuracion UUID PRIMARY KEY DEFAULT gen_random_uuid(),clave TEXT NOT NULL UNIQUE DEFAULT 'global',proveedor TEXT NOT NULL DEFAULT 'deepseek',base_url TEXT NOT NULL DEFAULT 'https://api.deepseek.com',modelo TEXT NOT NULL DEFAULT 'deepseek-chat',api_key_cifrada BYTEA,api_key_pista TEXT,habilitado BOOLEAN NOT NULL DEFAULT FALSE,max_iteraciones INTEGER NOT NULL DEFAULT 8 CHECK(max_iteraciones BETWEEN 1 AND 50),temperatura NUMERIC NOT NULL DEFAULT 0.2 CHECK(temperatura BETWEEN 0 AND 2),precios JSONB NOT NULL DEFAULT '{}'::jsonb,verificado_at TIMESTAMPTZ,verificado_ok BOOLEAN,verificado_detalle TEXT,updated_by UUID REFERENCES usuarios_laboratorio(id_usuario) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ia_politicas (id_politica UUID PRIMARY KEY DEFAULT gen_random_uuid(),clave TEXT NOT NULL UNIQUE,nombre TEXT NOT NULL,prompt_sistema TEXT NOT NULL,reglas JSONB NOT NULL DEFAULT '[]'::jsonb,dominios_permitidos TEXT[] NOT NULL DEFAULT '{}',dominios_bloqueados TEXT[] NOT NULL DEFAULT '{}',herramientas_habilitadas TEXT[] NOT NULL DEFAULT '{}',comandos_bloqueados TEXT[] NOT NULL DEFAULT '{}',max_iteraciones INTEGER NOT NULL DEFAULT 8,activa BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ia_conectores (id_conector UUID PRIMARY KEY DEFAULT gen_random_uuid(),clave TEXT NOT NULL UNIQUE,nombre TEXT NOT NULL,tipo TEXT NOT NULL CHECK(tipo IN ('busqueda_web','mcp','http','doi')),base_url TEXT NOT NULL,api_key_cifrada BYTEA,configuracion JSONB NOT NULL DEFAULT '{}'::jsonb,habilitado BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ia_conversaciones (id_conversacion UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_usuario UUID NOT NULL REFERENCES usuarios_laboratorio(id_usuario) ON DELETE CASCADE,id_politica UUID REFERENCES ia_politicas(id_politica) ON DELETE SET NULL,titulo TEXT,modo TEXT NOT NULL DEFAULT 'ask' CHECK(modo IN ('ask','agente','super')),shell_habilitado BOOLEAN NOT NULL DEFAULT FALSE,tokens_entrada BIGINT NOT NULL DEFAULT 0,tokens_salida BIGINT NOT NULL DEFAULT 0,costo_acumulado NUMERIC NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ia_mensajes (id_mensaje UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_conversacion UUID NOT NULL REFERENCES ia_conversaciones(id_conversacion) ON DELETE CASCADE,rol TEXT NOT NULL CHECK(rol IN ('system','user','assistant','tool')),contenido TEXT,tool_calls JSONB NOT NULL DEFAULT '[]'::jsonb,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,tokens_entrada INTEGER,tokens_salida INTEGER,costo NUMERIC,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ia_ejecuciones (id_ejecucion UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_conversacion UUID NOT NULL REFERENCES ia_conversaciones(id_conversacion) ON DELETE CASCADE,id_usuario UUID NOT NULL REFERENCES usuarios_laboratorio(id_usuario) ON DELETE CASCADE,estado TEXT NOT NULL DEFAULT 'pendiente' CHECK(estado IN ('pendiente','ejecutando','completada','error','cancelada')),modo TEXT NOT NULL CHECK(modo IN ('ask','agente','super')),error TEXT,iniciada_at TIMESTAMPTZ,finalizada_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ia_llamadas_herramienta (id_llamada UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_ejecucion UUID NOT NULL REFERENCES ia_ejecuciones(id_ejecucion) ON DELETE CASCADE,nombre TEXT NOT NULL,argumentos JSONB NOT NULL DEFAULT '{}'::jsonb,resultado JSONB,estado TEXT NOT NULL DEFAULT 'propuesta' CHECK(estado IN ('propuesta','aprobada','rechazada','ejecutada','error','cancelada','expirada')),requiere_aprobacion BOOLEAN NOT NULL DEFAULT FALSE,error TEXT,creada_at TIMESTAMPTZ NOT NULL DEFAULT now(),resuelta_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS ia_ejecuciones_shell (id_shell UUID PRIMARY KEY DEFAULT gen_random_uuid(),id_llamada UUID REFERENCES ia_llamadas_herramienta(id_llamada) ON DELETE SET NULL,id_ejecucion UUID NOT NULL REFERENCES ia_ejecuciones(id_ejecucion) ON DELETE CASCADE,comando TEXT NOT NULL,argv JSONB NOT NULL DEFAULT '[]'::jsonb,cwd TEXT,stdout TEXT,stderr TEXT,codigo_salida INTEGER,duracion_ms INTEGER,truncado BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_ia_conversaciones_usuario ON ia_conversaciones(id_usuario,updated_at DESC); CREATE INDEX IF NOT EXISTS idx_ia_mensajes_conversacion ON ia_mensajes(id_conversacion,created_at);
INSERT INTO ia_configuracion(clave) VALUES('global') ON CONFLICT(clave) DO NOTHING;
INSERT INTO ia_politicas(clave,nombre,prompt_sistema,reglas,dominios_permitidos,dominios_bloqueados,herramientas_habilitadas,comandos_bloqueados) VALUES('predeterminada','Política predeterminada','Eres el asistente de FagoLab. No inventes datos de laboratorio; cita siempre la fuente y resuelve DOI mediante Crossref.','["No inventar datos de laboratorio","Citar siempre la fuente","Resolver DOI vía Crossref"]','{api.crossref.org,ncbi.nlm.nih.gov,doi.org,nature.com,science.org,sciencedirect.com,springer.com,wiley.com}','{localhost,127.0.0.1,169.254.169.254}','{}','{}') ON CONFLICT(clave) DO UPDATE SET nombre=EXCLUDED.nombre,prompt_sistema=EXCLUDED.prompt_sistema,reglas=EXCLUDED.reglas,dominios_permitidos=EXCLUDED.dominios_permitidos,dominios_bloqueados=EXCLUDED.dominios_bloqueados;
INSERT INTO ia_conectores(clave,nombre,tipo,base_url,habilitado) VALUES('brave','Brave Search','busqueda_web','https://api.search.brave.com',FALSE),('crossref','Crossref','doi','https://api.crossref.org',TRUE) ON CONFLICT(clave) DO UPDATE SET nombre=EXCLUDED.nombre,tipo=EXCLUDED.tipo,base_url=EXCLUDED.base_url,habilitado=EXCLUDED.habilitado;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_ia_configuracion_updated_at') THEN CREATE TRIGGER trg_ia_configuracion_updated_at BEFORE UPDATE ON ia_configuracion FOR EACH ROW EXECUTE FUNCTION set_updated_at(); END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='trg_ia_conversaciones_updated_at') THEN CREATE TRIGGER trg_ia_conversaciones_updated_at BEFORE UPDATE ON ia_conversaciones FOR EACH ROW EXECUTE FUNCTION set_updated_at(); END IF;
END $$;
